### ISSUE TITLE
poor error when failing authorization due to lack of email address

### ISSUE THREAD

**Issue by keyvanfatehi** [Strider-CD/strider-github#25]
There is this error, which is apparently no longer thrown if you set your email address correctly in github.

Code there needs to be inspected and determined if a better error can be thrown, e.g. "You need to enter your email address into Github."

```
Express
500 TypeError: Cannot read property '0' of undefined
at makeAccount (/Users/Hamid/Developer/strider/node_modules/strider-github/lib/webapp.js:167:28)
at Strategy.validateAuth as _verify
at /Users/Hamid/Developer/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/lib/strategy.js:188:22
at /Users/Hamid/Developer/strider/node_modules/strider-github/node_modules/passport-github/lib/strategy.js:109:5
at passBackControl (/Users/Hamid/Developer/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:126:9)
at IncomingMessage. (/Users/Hamid/Developer/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
at IncomingMessage.EventEmitter.emit (events.js:117:20)
at _stream_readable.js:920:16
at process._tickCallback (node.js:415:13)
```

Ref original issue: https://github.com/Strider-CD/strider/issues/599

**Comment by SamMorrowDrums** [comment]
https://github.com/Strider-CD/strider-github/pull/28

**Comment by knownasilya** [comment]
Fixed in 9bc4bfa8bcf59f691f08bd45d3be7f868fc735b3

**Comment by briandela** [comment]
I'm still seeing this on the latest master. I just cloned everything and when I try to connect to github I get:

```
TypeError: Cannot read property '0' of undefined
   at makeAccount (/Users/brian/outhouse/strider/node_modules/strider-github/lib/webapp.js:167:28)
   at Strategy.validateAuth [as _verify] (/Users/brian/outhouse/strider/node_modules/strider-github/lib/webapp.js:152:26)
   at /Users/brian/outhouse/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/lib/strategy.js:188:22
   at /Users/brian/outhouse/strider/node_modules/strider-github/node_modules/passport-github/lib/strategy.js:109:5
   at passBackControl (/Users/brian/outhouse/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:126:9)
   at IncomingMessage.<anonymous> (/Users/brian/outhouse/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
   at IncomingMessage.emit (events.js:129:20)
   at _stream_readable.js:908:16
   at process._tickCallback (node.js:355:11)
```

Any ideas?

**Comment by knownasilya** [comment]
Do you have a public email set for your github account?

On Fri, Feb 13, 2015 at 1:40 PM, Brian Delahunty <notifications@github.com>
wrote:

> I'm still seeing this on the latest master. I just cloned everything and
> when I try to connect to github I get:
>
> TypeError: Cannot read property '0' of undefined
>    at makeAccount (/Users/brian/outhouse/strider/node_modules/strider-github/lib/webapp.js:167:28)
>    at Strategy.validateAuth [as _verify] (/Users/brian/outhouse/strider/node_modules/strider-github/lib/webapp.js:152:26)
>    at /Users/brian/outhouse/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/lib/strategy.js:188:22
>    at /Users/brian/outhouse/strider/node_modules/strider-github/node_modules/passport-github/lib/strategy.js:109:5
>    at passBackControl (/Users/brian/outhouse/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:126:9)
>    at IncomingMessage.<anonymous> (/Users/brian/outhouse/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
>    at IncomingMessage.emit (events.js:129:20)
>    at _stream_readable.js:908:16
>    at process._tickCallback (node.js:355:11)
>
> Any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Strider-CD/strider-github/issues/25#issuecomment-74303643>
> .
>



-- 
*Ilya Radchenko*
*Application Developer*
617-447-2425 Direct | 617-447-2400 Main
Applied Geographics, Inc.
24 School Street, Suite 500
Boston, MA 02108
www.AppGeo.com

-- 
This e-mail message and any attachments may contain confidential or legally 
privileged information. If you are not an intended recipient or otherwise 
authorized to receive this message, you should not use, copy, distribute, 
disclose or take any action based on the information contained in this 
e-mail or any attachments. If you have received this message and material 
in error, please advise the sender immediately by reply e-mail and delete 
this message. Thank you on behalf of Applied Geographics, Inc. (AppGeo).

**Comment by briandela** [comment]
Yep - it's not the same as the login I used for strider (my strider login is a private email on my github but I do have a public email)

**Comment by knownasilya** [comment]
@briandela what version of strider-github are you using?

**Comment by briandela** [comment]
I did a `git clone` of it this morning.

**Comment by briandela** [comment]
I found the issue - github was showing my email as Public when I went to emails, but in another part of my profile it was showing as private. I set everything up as public again and it's working now.

**Comment by knownasilya** [comment]
nice. I thought we fixed this issue, guess not..

**Comment by smilledge** [comment]
For anyone else who is having this problem you need to go to https://github.com/settings/profile and select an email under "Public email".

**Comment by knownasilya** [comment]
@smilledge I added your suggestion to the README

**Comment by ellerbrock** [comment]
yupp, same here.
just wanted to get started with strider, cloned the repository, updated all the plugins and then baam `500 Error: You need to enter your email address into Github.` to this one too :(

i tried to comment quick and dirty few things out but not too successful (also don't want to spend to much time on this subject). 

here a workaround how you can get connected to github:


- go to your github profile settings: <https://github.com/settings/profile>
- change public email from `don't show my email bla bla` to show
- probably you should set this email the same like the one you are using for your strider user.
inside strider you can change the email in your account setting <http://localhost:3000/account>
- last thing to do uncheck `Keep my email address private`<https://github.com/settings/emails>

after changing this i could register strider to github which make me now a happy nerd again :)
was already on my way to gave up and opened drone ci :)

in my opinion it would help the project a lot if people can more easy start and play with strider.
i would suggest change this breaking things as quick as possible or make it very clear for the user how to get things up. nothing more worse starting with some code and straight run n issues.
also i saw for example the plugin list was not updated and you run in an error trying to install the `hq` plugin (repo doesn't exist anymore). a auto update or update all function would be great. my starting point was to copy all the links and type the same upgrade over and over. this is the part where i in the web world normaly would write a small scrapper or so to automate this :)

by the way, my first starting point was a complet other way.
i was happy to see you have a docker image running.
first at all i did not find how to log in and find the default user and password somewhere on another site writing about this. this should be very clear for every newcomer.
second even after starting docker with all the enviroment variables setup i could not get stuff running that it save the changes in the mongodb so i gave up and came here.

ok so this was a lot complaining and sorry for that.
you all working to make a good peace of software and open source it so i just want to help that you not lose all the users to other systems.

i could offer my help to figure out a way to get a current strider version deployed with each stable release. the next thing i would update would be the documentation how to get it quick and easy running. let's be honest the documentation on docker (https://hub.docker.com/r/strider/strider/) hub is quite poor :) 

cheerio js friends

**Comment by knownasilya** [comment]
Thanks for your feedback. We welcome any contributions, especially documentation.

I've started working on a guides website, but have been busy since I became a father  2 days ago.

Feel free to submit a PR for the update all plugins feature. Look in the lib/routes and in strider-cli

**Comment by ellerbrock** [comment]
hey that are great news, congratulations!
all the best wishes to you and your new family.
my little git clone is still in alpha version happy inside the belly from mami, spring next year its time or me go afk a while :)

i really was looking forward to play with strider but had quite a hassle and like i wrote was more or less on the way to try drone as alternative to the old heavyweight jenkins we used so far.

one thing i think really important to the project would be to collect in the first place on a central spot where in the setup / installation stuff things are breaking and fix them. i saw so far the problem with the docker image (and would suggest i create a new one if you are ok with this and make a easy to understand documentation how to get strider up in running under 10min).

i would quick try to find and drop the plugin which doesn't exist anymore and make a pull request.
the second thing is how to handle the docker image? i have a dockhub account <https://hub.docker.com/u/frapsoft/> and since yesterday night a quay.io account too <https://quay.io/user/ellerbrock>. i need to have a look first what you done so far and how to set things up that they work smooff with your ci / cd system. so i consider you run strider for your own projects as well? its my first contact with strider so i will play on my so much loved 127.0.0.1 dreamland a while first. when things looks good i will come back to you guys with a hopefully working solution ...
